# Generated by Django 5.1.3 on 2025-07-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BondFutureCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bond_price", models.FloatField()),
                ("interest_rate", models.FloatField()),
                ("maturity_years", models.FloatField()),
                ("future_price", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
