# Generated by Django 5.1.3 on 2025-07-06 17:52

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BondFutureCalculation",
        ),
    ]
